image: javiersantos/android-ci:27.0.3

variables:
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"

before_script:
    - chmod +x ./gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/

stages:
  - build

build:
  stage: build
  script:
     - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/
